package com.ubb.backend.model;

import java.util.Arrays;
import java.util.List;
import java.util.Random;

public class RealLocation {
    private Random random = new Random();
    private List<String> locations = Arrays.asList(
            "Abbey Road, London, United Kingdom",
            "Fifth Avenue, New York City, United States",
            "Champs-Élysées, Paris, France",
            "Via Monte Napoleone, Milan, Italy",
            "Potsdamer Platz, Berlin, Germany",
            "Rodeo Drive, Beverly Hills, United States",
            "Shibuya Crossing, Tokyo, Japan",
            "Las Ramblas, Barcelona, Spain",
            "Avenue des Champs-Élysées, Paris, France",
            "O'Connell Street, Dublin, Ireland",
            "Orchard Road, Singapore, Singapore",
            "Causeway Bay, Hong Kong, China",
            "La Rambla, Barcelona, Spain",
            "Bourbon Street, New Orleans, United States",
            "Ocean Drive, Miami Beach, United States",
            "Kurfürstendamm, Berlin, Germany",
            "Avenida Paulista, São Paulo, Brazil",
            "Rua Oscar Freire, São Paulo, Brazil",
            "Khao San Road, Bangkok, Thailand",
            "The Strip, Las Vegas, United States",
            "Rua Augusta, Lisbon, Portugal",
            "Avenida Corrientes, Buenos Aires, Argentina",
            "Váci Street, Budapest, Hungary",
            "Tverskaya Street, Moscow, Russia",
            "Dam Square, Amsterdam, Netherlands",
            "Siam Paragon, Bangkok, Thailand",
            "Times Square, New York City, United States",
            "Pike Place Market, Seattle, United States",
            "Rua 25 de Março, São Paulo, Brazil",
            "Rua do Carmo, Lisbon, Portugal",
            "Nevsky Prospect, St. Petersburg, Russia",
            "Nanjing Road, Shanghai, China",
            "Leidseplein, Amsterdam, Netherlands",
            "Camden Market, London, United Kingdom",
            "Santa Monica Boulevard, Los Angeles, United States",
            "Myeongdong, Seoul, South Korea",
            "Istiklal Avenue, Istanbul, Turkey",
            "Bourbon Street, New Orleans, United States",
            "Khao San Road, Bangkok, Thailand",
            "Rua Augusta, Lisbon, Portugal",
            "Avenue des Champs-Élysées, Paris, France",
            "Orchard Road, Singapore, Singapore",
            "Via Monte Napoleone, Milan, Italy",
            "Rodeo Drive, Beverly Hills, United States",
            "La Rambla, Barcelona, Spain",
            "O'Connell Street, Dublin, Ireland",
            "Kurfürstendamm, Berlin, Germany",
            "Shibuya Crossing, Tokyo, Japan",
            "Abbey Road, London, United Kingdom",
            "Champs-Élysées, Paris, France",
            "Fifth Avenue, New York City, United States",
            "Potsdamer Platz, Berlin, Germany",
            "Las Ramblas, Barcelona, Spain",
            "Via Monte Napoleone, Milan, Italy",
            "Rodeo Drive, Beverly Hills, United States",
            "Shibuya Crossing, Tokyo, Japan",
            "O'Connell Street, Dublin, Ireland",
            "Orchard Road, Singapore, Singapore",
            "Causeway Bay, Hong Kong, China",
            "La Rambla, Barcelona, Spain",
            "Bourbon Street, New Orleans, United States",
            "Ocean Drive, Miami Beach, United States",
            "Kurfürstendamm, Berlin, Germany",
            "Avenida Paulista, São Paulo, Brazil",
            "Rua Oscar Freire, São Paulo, Brazil",
            "Khao San Road, Bangkok, Thailand",
            "The Strip, Las Vegas, United States",
            "Rua Augusta, Lisbon, Portugal",
            "Avenida Corrientes, Buenos Aires, Argentina",
            "Váci Street, Budapest, Hungary",
            "Tverskaya Street, Moscow, Russia",
            "Dam Square, Amsterdam, Netherlands",
            "Siam Paragon, Bangkok, Thailand",
            "Times Square, New York City, United States",
            "Pike Place Market, Seattle, United States",
            "Rua 25 de Março, São Paulo, Brazil",
            "Rua do Carmo, Lisbon, Portugal",
            "Nevsky Prospect, St. Petersburg, Russia",
            "Nanjing Road, Shanghai, China",
            "Leidseplein, Amsterdam, Netherlands",
            "Camden Market, London, United Kingdom",
            "Santa Monica Boulevard, Los Angeles, United States",
            "Myeongdong, Seoul, South Korea",
            "Istiklal Avenue, Istanbul, Turkey",
            "Bourbon Street, New Orleans, United States",
            "Khao San Road, Bangkok, Thailand",
            "Rua Augusta, Lisbon, Portugal",
            "Avenue des Champs-Élysées, Paris, France",
            "Orchard Road, Singapore, Singapore",
            "Via Monte Napoleone, Milan, Italy",
            "Rodeo Drive, Beverly Hills, United States",
            "La Rambla, Barcelona, Spain",
            "O'Connell Street, Dublin, Ireland",
            "Kurfürstendamm, Berlin, Germany",
            "Shibuya Crossing, Tokyo, Japan",
            "Abbey Road, London, United Kingdom",
            "Champs-Élysées, Paris, France",
            "Fifth Avenue, New York City, United States",
            "Potsdamer Platz, Berlin, Germany",
            "Las Ramblas, Barcelona, Spain",
            "Via Monte Napoleone, Milan, Italy",
            "Rodeo Drive, Beverly Hills, United States",
            "Shibuya Crossing, Tokyo, Japan",
            "O'Connell Street, Dublin, Ireland",
            "Orchard Road, Singapore, Singapore",
            "Causeway Bay, Hong Kong, China",
            "La Rambla, Barcelona, Spain",
            "Bourbon Street, New Orleans, United States",
            "Ocean Drive, Miami Beach, United States",
            "Kurfürstendamm, Berlin, Germany",
            "Avenida Paulista, São Paulo, Brazil",
            "Rua Oscar Freire, São Paulo, Brazil",
            "Khao San Road, Bangkok, Thailand",
            "The Strip, Las Vegas, United States",
            "Rua Augusta, Lisbon, Portugal",
            "Avenida Corrientes, Buenos Aires, Argentina",
            "Váci Street, Budapest, Hungary",
            "Tverskaya Street, Moscow, Russia",
            "Dam Square, Amsterdam, Netherlands",
            "Siam Paragon, Bangkok, Thailand",
            "Times Square, New York City, United States",
            "Pike Place Market, Seattle, United States",
            "Rua 25 de Março, São Paulo, Brazil",
            "Rua do Carmo, Lisbon, Portugal",
            "Nevsky Prospect, St. Petersburg, Russia",
            "Nanjing Road, Shanghai, China",
            "Leidseplein, Amsterdam, Netherlands",
            "Camden Market, London, United Kingdom",
            "Santa Monica Boulevard, Los Angeles, United States",
            "Myeongdong, Seoul, South Korea",
            "Istiklal Avenue, Istanbul, Turkey",
            "Bourbon Street, New Orleans, United States",
            "Khao San Road, Bangkok, Thailand",
            "Rua Augusta, Lisbon, Portugal",
            "Avenue des Champs-Élysées, Paris, France",
            "Orchard Road, Singapore, Singapore",
            "Via Monte Napoleone, Milan, Italy",
            "Rodeo Drive, Beverly Hills, United States",
            "La Rambla, Barcelona, Spain",
            "O'Connell Street, Dublin, Ireland",
            "Kurfürstendamm, Berlin, Germany",
            "Shibuya Crossing, Tokyo, Japan"
    );
    private int nrLocations = locations.size();

    public String getLocation()
    {
        return this.locations.get(random.nextInt(0, nrLocations));
    }

}
